name: colorful_progress_indicator
description: "Different progress indicator based on Gradients"
version: 0.1.0
repository: https://github.com/YukiAttano/colorful_progress_indicator
issue_tracker: https://github.com/YukiAttano/colorful_progress_indicator/issues
topics:
  - widget
  - ui
  - flutter


environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

